### ISSUE TITLE
Error installing Various Add ins

### ISSUE THREAD

**Issue by chicofish** [biolab/orange3#2615]
##### Orange version

3.5.0
git revision a75eb36

##### Expected behavior

installed add ins (Geo, network, image processing and others) - error message below just from Geo

##### Actual behavior

error

##### Steps to reproduce the behavior

simply "install add ins"

##### Additional info (worksheets, data, screenshots, ...)
On Windows 10. 
Works on Mac OS 10.x

Collecting Orange3-Geo
  Using cached Orange3-Geo-0.1.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "c:\users\username\appdata\local\continuum\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\__init__.py", line 10, in <module>
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "c:\users\username\appdata\local\continuum\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\extern\__init__.py", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "c:\users\username\appdata\local\continuum\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2985, in <module>
      File "c:\users\username\appdata\local\continuum\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2971, in _call_aside
      File "c:\users\username\appdata\local\continuum\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 3013, in _initialize_master_working_set
      File "c:\users\username\appdata\local\continuum\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2544, in activate
      File "c:\users\username\appdata\local\continuum\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2118, in declare_namespace
      File "c:\users\username\appdata\local\continuum\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2058, in _handle_ns
      File "c:\users\username\appdata\local\continuum\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2087, in _rebuild_mod_path
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\username\AppData\Local\Temp\1\pip-build-qzrzx8ym\Orange3-Geo\

**Comment by janezd** [comment]
Already fixed in #2602.

Running `pip3 install --upgrade setuptools` should fix the current installation.

**Comment by chicofish** [comment]
is there a conda version of the command?  I'm running this via Anaconda Navigator

**Comment by janezd** [comment]
I think you can or even should use pip. Orange also uses pip internally to install add ons.

**Comment by chicofish** [comment]
setuptools have been upgrade, machine restarted but the problem still persists

Collecting Orange3-Geo
  Using cached Orange3-Geo-0.1.8.tar.gz
Requirement already satisfied: Orange3 in c:\users\username\appdata\local\continuum\anaconda3\lib\site-packages (from Orange3-Geo)
Requirement already satisfied: scikit-learn in c:\users\username\appdata\local\continuum\anaconda3\lib\site-packages (from Orange3-Geo)
Requirement already satisfied: pandas in c:\users\username\appdata\local\continuum\anaconda3\lib\site-packages (from Orange3-Geo)
Requirement already satisfied: scipy>=0.17 in c:\users\username\appdata\local\continuum\anaconda3\lib\site-packages (from Orange3-Geo)
Collecting shapely (from Orange3-Geo)
  Using cached Shapely-1.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\username\AppData\Local\Temp\1\pip-build-7uepv9kq\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\username\AppData\Local\Temp\1\pip-build-7uepv9kq\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "c:\users\username\appdata\local\continuum\anaconda3\lib\ctypes\__init__.py", line 344, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\username\AppData\Local\Temp\1\pip-build-7uepv9kq\shapely\

**Comment by janezd** [comment]
This is a different problem. Before, the error was in the part that installs add-ons. Now, it is a particular add-on that fails, Geo. Can you open an issue at https://github.com/biolab/orange3-geo/issues? I mean, I could do it, but then you wouldn't get responses there.

**Comment by chicofish** [comment]
will do
