### ISSUE TITLE
"orange-canvas" command fails with import error in Orange 3

### ISSUE THREAD

**Issue by qingfengwuhen** [biolab/orange3#6843]
When attempting to run the "orange-canvas" command, I encountered an import error in Python that prevented me from running the app.

D:\Users\xxxxxxx\AppData\Local\anaconda3\envs\orange3_dev\python.exe F:/project/orange3/Orange/canvas/__main__.py
F:\project\orange3\Orange\canvas\__main__.py:19: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Traceback (most recent call last):
  File "F:\project\orange3\Orange\canvas\__main__.py", line 35, in <module>
    from Orange import canvas
  File "F:\project\orange3\Orange\__init__.py", line 4, in <module>
    from Orange import data
  File "F:\project\orange3\Orange\data\__init__.py", line 4, in <module>
    from .variable import *
  File "F:\project\orange3\Orange\data\variable.py", line 15, in <module>
    from Orange.data import _variable
ImportError: cannot import name '_variable' from partially initialized module 'Orange.data' (most likely due to a circular import) (F:\project\orange3\Orange\data\__init__.py)

**What's your environment?**

- Operating system: windows 10
- Orange version: 3.37
- How you installed Orange:  git clone  then pip install -e orange3

**Comment by janezd** [comment]
This is probably not a problem with Orange (and probably can't be resolved in Orange) but rather with something peculiar in your setup or the way you run Orange.

From which directory do you run `orange-canvas`? Can you cd to a completely unrelated directory? I cannot replicate your exact problem, but Python searches for modules in the current directory first, which can lead to problems.

Does `python -m Orange.canvas` work?

**Comment by janezd** [comment]
Closed due to inactivity.

**Comment by bsnresearcher** [comment]
Dear author

Would you help me.
I am bothered the same above trouble.

I tried to make environment to develop Orange3 on 
the my very simple manipulation(made venv, install required packages, clone orange3 source codes and tried to launch orange3).

However I met the same trouble.

This troubles were used to be caused by the same module name between on import/from and of pip packages.

But I could not find the module name caused my problem.
So please help me to solve this problem.

I submit the my log following below.

MyEnv.
- MacOS(Sillicon M1 CPU): 14.7.6（23H626）
- Conda: mambaforge


```bash

### cd to Target Path
(o3) (base) MyMacOS:orange3 my_user$ cd /Users/my_user/code_root/OrangeTry
direnv: unloading

(o3) (base) MyMacOS:OrangeTry my_user$ pwd
/Users/my_user/code_root/OrangeTry

### conda create
(o3) (base) MyMacOS:OrangeTry my_user$ conda config --set channel_priority strict
(o3) (base) MyMacOS:OrangeTry my_user$ conda create -n orange3try python==3.10
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
    current version: 24.3.0
    latest version: 25.5.1

Please update conda by running

    $ conda update -n base -c conda-forge conda



## Package Plan ##

  environment location: /opt/homebrew/Caskroom/mambaforge/base/envs/orange3try

  added / updated specs:
    - python==3.10


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bzip2-1.0.8                |       h99b78c6_7         120 KB  conda-forge
    icu-75.1                   |       hfee45f7_0        11.3 MB  conda-forge
    libffi-3.4.6               |       h1da3d7d_1          39 KB  conda-forge
    liblzma-5.8.1              |       h39f12f2_2          90 KB  conda-forge
    liblzma-devel-5.8.1        |       h39f12f2_2         114 KB  conda-forge
    libsqlite-3.50.3           |       h4237e3c_1         882 KB  conda-forge
    libzlib-1.3.1              |       h8359307_2          45 KB  conda-forge
    ncurses-6.5                |       h5e97a16_3         778 KB  conda-forge
    pip-25.1.1                 |     pyh8b19718_0         1.2 MB  conda-forge
    readline-8.2               |       h1d1bf99_2         246 KB  conda-forge
    sqlite-3.50.3              |       hb5dd463_1         146 KB  conda-forge
    tk-8.6.13                  |       h892fb3f_2         3.0 MB  conda-forge
    tzdata-2025b               |       h78e105d_0         120 KB  conda-forge
    xz-5.8.1                   |       h9a6d368_2          23 KB  conda-forge
    xz-gpl-tools-5.8.1         |       h9a6d368_2          33 KB  conda-forge
    xz-tools-5.8.1             |       h39f12f2_2          84 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        18.1 MB

The following NEW packages will be INSTALLED:

  bzip2              conda-forge/osx-arm64::bzip2-1.0.8-h99b78c6_7 
  ca-certificates    conda-forge/noarch::ca-certificates-2025.7.14-hbd8a1cb_0 
  icu                conda-forge/osx-arm64::icu-75.1-hfee45f7_0 
  libffi             conda-forge/osx-arm64::libffi-3.4.6-h1da3d7d_1 
  liblzma            conda-forge/osx-arm64::liblzma-5.8.1-h39f12f2_2 
  liblzma-devel      conda-forge/osx-arm64::liblzma-devel-5.8.1-h39f12f2_2 
  libsqlite          conda-forge/osx-arm64::libsqlite-3.50.3-h4237e3c_1 
  libzlib            conda-forge/osx-arm64::libzlib-1.3.1-h8359307_2 
  ncurses            conda-forge/osx-arm64::ncurses-6.5-h5e97a16_3 
  openssl            conda-forge/osx-arm64::openssl-3.5.1-h81ee809_0 
  pip                conda-forge/noarch::pip-25.1.1-pyh8b19718_0 
  python             conda-forge/osx-arm64::python-3.10.0-h43b31ca_3_cpython 
  readline           conda-forge/osx-arm64::readline-8.2-h1d1bf99_2 
  setuptools         conda-forge/noarch::setuptools-80.9.0-pyhff2d567_0 
  sqlite             conda-forge/osx-arm64::sqlite-3.50.3-hb5dd463_1 
  tk                 conda-forge/osx-arm64::tk-8.6.13-h892fb3f_2 
  tzdata             conda-forge/noarch::tzdata-2025b-h78e105d_0 
  wheel              conda-forge/noarch::wheel-0.45.1-pyhd8ed1ab_1 
  xz                 conda-forge/osx-arm64::xz-5.8.1-h9a6d368_2 
  xz-gpl-tools       conda-forge/osx-arm64::xz-gpl-tools-5.8.1-h9a6d368_2 
  xz-tools           conda-forge/osx-arm64::xz-tools-5.8.1-h39f12f2_2 


Proceed ([y]/n)? Y


Downloading and Extracting Packages:
                                                                                                                                                                                                             
Preparing transaction: done                                                                                                                                                                                  
Verifying transaction: done                                                                                                                                                                                  
Executing transaction: done                                                                                                                                                                                  
#                                                                                                                                                                                                            
# To activate this environment, use                                                                                                                                                                          
#                                                                                                                                                                                                            
#     $ conda activate orange3try                                                                                                                                                                            
#                                                                                                                                                                                                            
# To deactivate an active environment, use                                                                                                                                                                   
#                                                                                                                                                                                                            
#     $ conda deactivate                                                                                                                                                                                     
######################################################################## 
(o3) (base) MyMacOS:OrangeTry my_user$ conda activate orange3try 

######################################################################## 
(orange3try) (o3) MyMacOS:OrangeTry my_user$ git clone https://github.com/biolab/orange3.git                                                                                                            
Cloning into 'orange3'...                                                                                                                                                                                    
remote: Enumerating objects: 102982, done.
remote: Counting objects: 100% (1665/1665), done.
remote: Compressing objects: 100% (444/444), done.
remote: Total 102982 (delta 1425), reused 1227 (delta 1220), pack-reused 101317 (from 3)
Receiving objects: 100% (102982/102982), 100.43 MiB | 14.89 MiB/s, done.
Resolving deltas: 100% (79363/79363), done.

########################################################################
(orange3try) (o3) MyMacOS:OrangeTry my_user$ ls
orange3
########################################################################
(orange3try) (o3) MyMacOS:OrangeTry my_user$ cd orange3/
(orange3try) (o3) MyMacOS:orange3 my_user$ pip install -Ur requirements.txt 
Collecting baycomp>=1.0.2 (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 1))
  Using cached baycomp-1.0.3-py3-none-any.whl
Collecting bottleneck>=1.3.4 (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 2))
  Using cached bottleneck-1.5.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (8.1 kB)
Collecting chardet>=3.0.2 (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 4))
  Using cached chardet-5.2.0-py3-none-any.whl.metadata (3.4 kB)
Collecting httpx>=0.21.0 (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 5))
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting joblib>=1.2.0 (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 7))
  Using cached joblib-1.5.1-py3-none-any.whl.metadata (5.6 kB)
Collecting keyring (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 8))
  Using cached keyring-25.6.0-py3-none-any.whl.metadata (20 kB)
Collecting keyrings.alt (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 9))
  Using cached keyrings.alt-5.0.2-py3-none-any.whl.metadata (3.6 kB)
Collecting networkx (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 10))
  Using cached networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Collecting numpy>=1.21.0 (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 11))
  Using cached numpy-2.2.6-cp310-cp310-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting openpyxl>=3.1.3 (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 12))
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting openTSNE!=0.7.0,>=0.6.2 (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 13))
  Using cached openTSNE-1.0.2-cp310-cp310-macosx_10_12_universal2.whl.metadata (7.8 kB)
Collecting packaging (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 14))
  Using cached packaging-25.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pandas!=1.5.0,!=2.0.0,>=1.4.0 (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 15))
  Using cached pandas-2.3.1-cp310-cp310-macosx_11_0_arm64.whl.metadata (91 kB)
Collecting python-louvain>=0.13 (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 16))
  Using cached python_louvain-0.16-py3-none-any.whl
Collecting pyyaml (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 17))
  Using cached PyYAML-6.0.2-cp310-cp310-macosx_11_0_arm64.whl.metadata (2.1 kB)
Collecting requests (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 18))
  Using cached requests-2.32.4-py3-none-any.whl.metadata (4.9 kB)
Collecting scikit-learn>=1.5.1 (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 19))
  Using cached scikit_learn-1.7.1-cp310-cp310-macosx_12_0_arm64.whl.metadata (11 kB)
Collecting scipy>=1.9 (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 20))
  Using cached scipy-1.15.3-cp310-cp310-macosx_14_0_arm64.whl.metadata (61 kB)
Collecting serverfiles (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 21))
  Using cached serverfiles-0.3.1-py3-none-any.whl
Collecting xgboost<2.1,>=1.7.4 (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 22))
  Using cached xgboost-2.0.3-py3-none-macosx_12_0_arm64.whl.metadata (2.0 kB)
Collecting xlrd>=1.2.0 (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 24))
  Using cached xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting xlsxwriter (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 26))
  Using cached xlsxwriter-3.2.5-py3-none-any.whl.metadata (2.7 kB)
Collecting recommonmark (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-doc.txt (line 1))
  Using cached recommonmark-0.7.1-py2.py3-none-any.whl.metadata (463 bytes)
Collecting Sphinx<8,>=4.2.0 (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-doc.txt (line 2))
  Using cached sphinx-7.4.7-py3-none-any.whl.metadata (6.1 kB)
Collecting sphinx-multiproject (from -r /Users/my_user/code_root/OrangeTry/orange3/requirements-doc.txt (line 3))
  Using cached sphinx_multiproject-1.0.0-py3-none-any.whl.metadata (1.7 kB)
Collecting sphinxcontrib-applehelp (from Sphinx<8,>=4.2.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-doc.txt (line 2))
  Using cached sphinxcontrib_applehelp-2.0.0-py3-none-any.whl.metadata (2.3 kB)
Collecting sphinxcontrib-devhelp (from Sphinx<8,>=4.2.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-doc.txt (line 2))
  Using cached sphinxcontrib_devhelp-2.0.0-py3-none-any.whl.metadata (2.3 kB)
Collecting sphinxcontrib-jsmath (from Sphinx<8,>=4.2.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-doc.txt (line 2))
  Using cached sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting sphinxcontrib-htmlhelp>=2.0.0 (from Sphinx<8,>=4.2.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-doc.txt (line 2))
  Using cached sphinxcontrib_htmlhelp-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting sphinxcontrib-serializinghtml>=1.1.9 (from Sphinx<8,>=4.2.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-doc.txt (line 2))
  Using cached sphinxcontrib_serializinghtml-2.0.0-py3-none-any.whl.metadata (2.4 kB)
Collecting sphinxcontrib-qthelp (from Sphinx<8,>=4.2.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-doc.txt (line 2))
  Using cached sphinxcontrib_qthelp-2.0.0-py3-none-any.whl.metadata (2.3 kB)
Collecting Jinja2>=3.1 (from Sphinx<8,>=4.2.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-doc.txt (line 2))
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting Pygments>=2.17 (from Sphinx<8,>=4.2.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-doc.txt (line 2))
  Using cached pygments-2.19.2-py3-none-any.whl.metadata (2.5 kB)
Collecting docutils<0.22,>=0.20 (from Sphinx<8,>=4.2.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-doc.txt (line 2))
  Using cached docutils-0.21.2-py3-none-any.whl.metadata (2.8 kB)
Collecting snowballstemmer>=2.2 (from Sphinx<8,>=4.2.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-doc.txt (line 2))
  Using cached snowballstemmer-3.0.1-py3-none-any.whl.metadata (7.9 kB)
Collecting babel>=2.13 (from Sphinx<8,>=4.2.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-doc.txt (line 2))
  Using cached babel-2.17.0-py3-none-any.whl.metadata (2.0 kB)
Collecting alabaster~=0.7.14 (from Sphinx<8,>=4.2.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-doc.txt (line 2))
  Using cached alabaster-0.7.16-py3-none-any.whl.metadata (2.9 kB)
Collecting imagesize>=1.3 (from Sphinx<8,>=4.2.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-doc.txt (line 2))
  Using cached imagesize-1.4.1-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting tomli>=2 (from Sphinx<8,>=4.2.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-doc.txt (line 2))
  Using cached tomli-2.2.1-py3-none-any.whl.metadata (10 kB)
Collecting matplotlib>=2.1.2 (from baycomp>=1.0.2->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 1))
  Using cached matplotlib-3.10.3-cp310-cp310-macosx_11_0_arm64.whl.metadata (11 kB)
Collecting anyio (from httpx>=0.21.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 5))
  Using cached anyio-4.9.0-py3-none-any.whl.metadata (4.7 kB)
Collecting certifi (from httpx>=0.21.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 5))
  Using cached certifi-2025.7.14-py3-none-any.whl.metadata (2.4 kB)
Collecting httpcore==1.* (from httpx>=0.21.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 5))
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx>=0.21.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 5))
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx>=0.21.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 5))
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting importlib_metadata>=4.11.4 (from keyring->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 8))
  Using cached importlib_metadata-8.7.0-py3-none-any.whl.metadata (4.8 kB)
Collecting jaraco.classes (from keyring->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 8))
  Using cached jaraco.classes-3.4.0-py3-none-any.whl.metadata (2.6 kB)
Collecting jaraco.functools (from keyring->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 8))
  Using cached jaraco_functools-4.2.1-py3-none-any.whl.metadata (2.9 kB)
Collecting jaraco.context (from keyring->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 8))
  Using cached jaraco.context-6.0.1-py3-none-any.whl.metadata (4.1 kB)
Collecting et-xmlfile (from openpyxl>=3.1.3->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 12))
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Collecting python-dateutil>=2.8.2 (from pandas!=1.5.0,!=2.0.0,>=1.4.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 15))
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas!=1.5.0,!=2.0.0,>=1.4.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 15))
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas!=1.5.0,!=2.0.0,>=1.4.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 15))
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting charset_normalizer<4,>=2 (from requests->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 18))
  Using cached charset_normalizer-3.4.2-cp310-cp310-macosx_10_9_universal2.whl.metadata (35 kB)
Collecting urllib3<3,>=1.21.1 (from requests->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 18))
  Using cached urllib3-2.5.0-py3-none-any.whl.metadata (6.5 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn>=1.5.1->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 19))
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting commonmark>=0.8.1 (from recommonmark->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-doc.txt (line 1))
  Using cached commonmark-0.9.1-py2.py3-none-any.whl.metadata (5.7 kB)
Collecting zipp>=3.20 (from importlib_metadata>=4.11.4->keyring->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 8))
  Using cached zipp-3.23.0-py3-none-any.whl.metadata (3.6 kB)
Collecting MarkupSafe>=2.0 (from Jinja2>=3.1->Sphinx<8,>=4.2.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-doc.txt (line 2))
  Using cached MarkupSafe-3.0.2-cp310-cp310-macosx_11_0_arm64.whl.metadata (4.0 kB)
Collecting contourpy>=1.0.1 (from matplotlib>=2.1.2->baycomp>=1.0.2->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 1))
  Using cached contourpy-1.3.2-cp310-cp310-macosx_11_0_arm64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib>=2.1.2->baycomp>=1.0.2->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 1))
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib>=2.1.2->baycomp>=1.0.2->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 1))
  Using cached fonttools-4.59.0-cp310-cp310-macosx_10_9_universal2.whl.metadata (107 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib>=2.1.2->baycomp>=1.0.2->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 1))
  Using cached kiwisolver-1.4.8-cp310-cp310-macosx_11_0_arm64.whl.metadata (6.2 kB)
Collecting pillow>=8 (from matplotlib>=2.1.2->baycomp>=1.0.2->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 1))
  Using cached pillow-11.3.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (9.0 kB)
Collecting pyparsing>=2.3.1 (from matplotlib>=2.1.2->baycomp>=1.0.2->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 1))
  Using cached pyparsing-3.2.3-py3-none-any.whl.metadata (5.0 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas!=1.5.0,!=2.0.0,>=1.4.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 15))
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting exceptiongroup>=1.0.2 (from anyio->httpx>=0.21.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 5))
  Using cached exceptiongroup-1.3.0-py3-none-any.whl.metadata (6.7 kB)
Collecting sniffio>=1.1 (from anyio->httpx>=0.21.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 5))
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting typing_extensions>=4.5 (from anyio->httpx>=0.21.0->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 5))
  Using cached typing_extensions-4.14.1-py3-none-any.whl.metadata (3.0 kB)
Collecting more-itertools (from jaraco.classes->keyring->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 8))
  Using cached more_itertools-10.7.0-py3-none-any.whl.metadata (37 kB)
Collecting backports.tarfile (from jaraco.context->keyring->-r /Users/my_user/code_root/OrangeTry/orange3/requirements-core.txt (line 8))
  Using cached backports.tarfile-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Using cached xgboost-2.0.3-py3-none-macosx_12_0_arm64.whl (1.9 MB)
Using cached sphinx-7.4.7-py3-none-any.whl (3.4 MB)
Using cached alabaster-0.7.16-py3-none-any.whl (13 kB)
Using cached docutils-0.21.2-py3-none-any.whl (587 kB)
Using cached bottleneck-1.5.0-cp310-cp310-macosx_11_0_arm64.whl (99 kB)
Using cached chardet-5.2.0-py3-none-any.whl (199 kB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Using cached joblib-1.5.1-py3-none-any.whl (307 kB)
Using cached keyring-25.6.0-py3-none-any.whl (39 kB)
Using cached keyrings.alt-5.0.2-py3-none-any.whl (17 kB)
Using cached networkx-3.4.2-py3-none-any.whl (1.7 MB)
Using cached numpy-2.2.6-cp310-cp310-macosx_14_0_arm64.whl (5.3 MB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached openTSNE-1.0.2-cp310-cp310-macosx_10_12_universal2.whl (1.0 MB)
Using cached packaging-25.0-py3-none-any.whl (66 kB)
Using cached pandas-2.3.1-cp310-cp310-macosx_11_0_arm64.whl (10.8 MB)
Using cached PyYAML-6.0.2-cp310-cp310-macosx_11_0_arm64.whl (171 kB)
Using cached requests-2.32.4-py3-none-any.whl (64 kB)
Using cached charset_normalizer-3.4.2-cp310-cp310-macosx_10_9_universal2.whl (201 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached urllib3-2.5.0-py3-none-any.whl (129 kB)
Using cached scikit_learn-1.7.1-cp310-cp310-macosx_12_0_arm64.whl (8.7 MB)
Using cached scipy-1.15.3-cp310-cp310-macosx_14_0_arm64.whl (22.4 MB)
Using cached xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Using cached xlsxwriter-3.2.5-py3-none-any.whl (172 kB)
Using cached recommonmark-0.7.1-py2.py3-none-any.whl (10 kB)
Using cached sphinx_multiproject-1.0.0-py3-none-any.whl (4.7 kB)
Using cached babel-2.17.0-py3-none-any.whl (10.2 MB)
Using cached certifi-2025.7.14-py3-none-any.whl (162 kB)
Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached imagesize-1.4.1-py2.py3-none-any.whl (8.8 kB)
Using cached importlib_metadata-8.7.0-py3-none-any.whl (27 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached MarkupSafe-3.0.2-cp310-cp310-macosx_11_0_arm64.whl (12 kB)
Using cached matplotlib-3.10.3-cp310-cp310-macosx_11_0_arm64.whl (8.0 MB)
Using cached contourpy-1.3.2-cp310-cp310-macosx_11_0_arm64.whl (253 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.59.0-cp310-cp310-macosx_10_9_universal2.whl (2.8 MB)
Using cached kiwisolver-1.4.8-cp310-cp310-macosx_11_0_arm64.whl (65 kB)
Using cached pillow-11.3.0-cp310-cp310-macosx_11_0_arm64.whl (4.7 MB)
Using cached pygments-2.19.2-py3-none-any.whl (1.2 MB)
Using cached pyparsing-3.2.3-py3-none-any.whl (111 kB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Using cached snowballstemmer-3.0.1-py3-none-any.whl (103 kB)
Using cached sphinxcontrib_htmlhelp-2.1.0-py3-none-any.whl (98 kB)
Using cached sphinxcontrib_serializinghtml-2.0.0-py3-none-any.whl (92 kB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached tomli-2.2.1-py3-none-any.whl (14 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Using cached zipp-3.23.0-py3-none-any.whl (10 kB)
Using cached anyio-4.9.0-py3-none-any.whl (100 kB)
Using cached exceptiongroup-1.3.0-py3-none-any.whl (16 kB)
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Using cached typing_extensions-4.14.1-py3-none-any.whl (43 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Using cached jaraco.classes-3.4.0-py3-none-any.whl (6.8 kB)
Using cached jaraco.context-6.0.1-py3-none-any.whl (6.8 kB)
Using cached backports.tarfile-1.2.0-py3-none-any.whl (30 kB)
Using cached jaraco_functools-4.2.1-py3-none-any.whl (10 kB)
Using cached more_itertools-10.7.0-py3-none-any.whl (65 kB)
Using cached sphinxcontrib_applehelp-2.0.0-py3-none-any.whl (119 kB)
Using cached sphinxcontrib_devhelp-2.0.0-py3-none-any.whl (82 kB)
Using cached sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (5.1 kB)
Using cached sphinxcontrib_qthelp-2.0.0-py3-none-any.whl (88 kB)
Installing collected packages: pytz, commonmark, zipp, xlsxwriter, xlrd, urllib3, tzdata, typing_extensions, tomli, threadpoolctl, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, sphinx-multiproject, snowballstemmer, sniffio, six, pyyaml, pyparsing, Pygments, pillow, packaging, numpy, networkx, more-itertools, MarkupSafe, kiwisolver, joblib, imagesize, idna, h11, fonttools, et-xmlfile, docutils, cycler, charset_normalizer, chardet, certifi, backports.tarfile, babel, alabaster, scipy, requests, python-louvain, python-dateutil, openpyxl, Jinja2, jaraco.functools, jaraco.context, jaraco.classes, importlib_metadata, httpcore, exceptiongroup, contourpy, bottleneck, xgboost, Sphinx, serverfiles, scikit-learn, pandas, matplotlib, keyrings.alt, keyring, anyio, recommonmark, openTSNE, httpx, baycomp
Successfully installed Jinja2-3.1.6 MarkupSafe-3.0.2 Pygments-2.19.2 Sphinx-7.4.7 alabaster-0.7.16 anyio-4.9.0 babel-2.17.0 backports.tarfile-1.2.0 baycomp-1.0.3 bottleneck-1.5.0 certifi-2025.7.14 chardet-5.2.0 charset_normalizer-3.4.2 commonmark-0.9.1 contourpy-1.3.2 cycler-0.12.1 docutils-0.21.2 et-xmlfile-2.0.0 exceptiongroup-1.3.0 fonttools-4.59.0 h11-0.16.0 httpcore-1.0.9 httpx-0.28.1 idna-3.10 imagesize-1.4.1 importlib_metadata-8.7.0 jaraco.classes-3.4.0 jaraco.context-6.0.1 jaraco.functools-4.2.1 joblib-1.5.1 keyring-25.6.0 keyrings.alt-5.0.2 kiwisolver-1.4.8 matplotlib-3.10.3 more-itertools-10.7.0 networkx-3.4.2 numpy-2.2.6 openTSNE-1.0.2 openpyxl-3.1.5 packaging-25.0 pandas-2.3.1 pillow-11.3.0 pyparsing-3.2.3 python-dateutil-2.9.0.post0 python-louvain-0.16 pytz-2025.2 pyyaml-6.0.2 recommonmark-0.7.1 requests-2.32.4 scikit-learn-1.7.1 scipy-1.15.3 serverfiles-0.3.1 six-1.17.0 sniffio-1.3.1 snowballstemmer-3.0.1 sphinx-multiproject-1.0.0 sphinxcontrib-applehelp-2.0.0 sphinxcontrib-devhelp-2.0.0 sphinxcontrib-htmlhelp-2.1.0 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-2.0.0 sphinxcontrib-serializinghtml-2.0.0 threadpoolctl-3.6.0 tomli-2.2.1 typing_extensions-4.14.1 tzdata-2025.2 urllib3-2.5.0 xgboost-2.0.3 xlrd-2.0.2 xlsxwriter-3.2.5 zipp-3.23.0

########################################################################
(orange3try) (o3) MyMacOS:orange3 my_user$ python -m Orage.canvas
/opt/homebrew/Caskroom/mambaforge/base/envs/orange3try/bin/python: Error while finding module specification for 'Orage.canvas' (ModuleNotFoundError: No module named 'Orage')
(orange3try) (o3) MyMacOS:orange3 my_user$ ls
CHANGELOG.md                    README-dev.md                   conda-recipe                    quietunittest.py                requirements-readthedocs.txt    tox.ini
CODE_OF_CONDUCT.md              README.md                       distribute                      requirements-core.txt           requirements-sql.txt            tutorials
CONTRIBUTING.md                 README.pypi                     doc                             requirements-dev.txt            requirements.txt
LICENSE                         ROADMAP.md                      i18n                            requirements-doc.txt            scripts
MANIFEST.in                     benchmark                       pylintrc                        requirements-gui.txt            setup.cfg
Orange                          codecov.yml                     pyproject.toml                  requirements-pyqt.txt           setup.py
(orange3try) (o3) MyMacOS:orange3 my_user$ python -m Orange.canvas
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/orange3try/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/orange3try/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/Users/my_user/code_root/OrangeTry/orange3/Orange/__init__.py", line 4, in <module>
    from Orange import data
  File "/Users/my_user/code_root/OrangeTry/orange3/Orange/data/__init__.py", line 4, in <module>
    from .variable import *
  File "/Users/my_user/code_root/OrangeTry/orange3/Orange/data/variable.py", line 16, in <module>
    from Orange.data import _variable
ImportError: cannot import name '_variable' from partially initialized module 'Orange.data' (most likely due to a circular import) (/Users/my_user/code_root/OrangeTry/orange3/Orange/data/__init__.py)
```

**Comment by markotoplak** [comment]
You are missing installation of Orange. You can't run it directly because some parts need to be compiled. To make a dev install (to compile stuff in place), try `pip install -e .` in Orange's downloaded folder.

You will also need to install PyQt5 or PyQt6 (that one is not in the requirements).

**Comment by markotoplak** [comment]
And, by the way, are you doing a development install intentionally? Otherwise there are dmg packages available at orangedatamining.com or - if you want it in a conda environenment - `conda install orange3` or `pip install orange3` for a pip-based python environment.

**Comment by bsnresearcher** [comment]
Dear markotoplak

> And, by the way, are you doing a development install intentionally? 
Yes. I want to develop a translated orange canvas to our language. ( I want customize msg.jaml via trubar and launch the translated oc3)

In my knowledge, The installation of `conda install orange3` or `pip install orange3` cannot provide to develop on the above.

Thank you.

**Comment by markotoplak** [comment]
OK, I understand.

The development install does not install translations automatically. To test them, you will need to execute trubar manually (more complicated) or do `pip install .` to install the version with translations into your python environment.

Also, as a first step in translation you will need to translate orange-canvas-core; not completely, but you'll at least need to register your language there.

Please don't hesitate to ask for help in setting this up. Unfortunately, we don't have a tutorial for translators yet...

**Comment by bsnresearcher** [comment]
Dear markotoplak

I prepared some translated msg.jaml files.

So I want to make sure for my msg.jaml to translate orange.canvas as I aim to intend.

**Comment by bsnresearcher** [comment]
Dear markotoplak

I prepared some translated msg.jaml files.

So I want to "launch orange.canvas applied my msg.jaml" to make sure for my msg.jaml to translate orange.canvas as I aim to intend. 

Thank you.

**Comment by janezd** [comment]
I implemented this some time ago, and I forgot the details. But as far as I can remember and decode it goes like this.

- Create a directory 'jp' (assuming you're translating to Japanese) as a sibling of 'si' and put your msgs.jaml file there
- Edit trubar-config.yaml to include a something like

   ```
  jp:
    name: 日本語
    international-name: Japanese
   ```

   Slovenian version also add functions that take care of plural forms, declensions and similar. You probably won't need anything similar, I think.

- Running `pip install .` should then install Orange that will offer Japanese as one of languages.

If you run into any problems, please don't hesitate to ask. If you wish, you can also send your translations and I'd be happy can try them myself.

**Comment by bsnresearcher** [comment]
Dear janezd

I did not know your advice, so if you did not advice me, I would be bothered.
Thank you very much.

I will beg your advice in this August after preparation for msgs.jaml.

**Comment by markotoplak** [comment]
@bsnresearcher, perhaps, at first, translate just a few of the strings (just enough to test if you can run it), so that we can help you bring everything together. Then, of course, you can take as much time as you need for the rest of the translation.

**Comment by bsnresearcher** [comment]
Dear markotoplak

I received your advice.

**Comment by bsnresearcher** [comment]
Excuse me, would you help me?

I tried to solve the below error, but have not solved.

1. I installed boost by conda to solve #include <map> # c?/c++'s std::map?
2. I reinstall xcode-select --install
3. sudo xcode-select --reset
4. brew install gcc

MyEnv.
- MacOS(Sillicon M1 CPU): 14.7.6（23H626）
- Conda: mambaforge


```bash
pip install .
...
(omission...)
...
Building wheels for collected packages: Orange3
  Building wheel for Orange3 (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for Orange3 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [938 lines of output]
      /private/var/folders/cb/lfh8rrms5ls0kwx5ks1c7pn00000gn/T/pip-build-env-vz64b9xu/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py:289: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      /private/var/folders/cb/lfh8rrms5ls0kwx5ks1c7pn00000gn/T/pip-build-env-vz64b9xu/overlay/lib/python3.10/site-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.
      !!
      
              ********************************************************************************
              Please consider removing the following classifiers in favor of a SPDX license expression:
      
              License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)
      
              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
              ********************************************************************************
      
      !!
        self._finalize_license_expression()
      running bdist_wheel
      running build
      running build_py
      copying Orange/tree.py -> build/lib.macosx-11.0-arm64-cpython-310/Orange
      copying Orange/version.py -> build/lib.macosx-11.0-arm64-cpython-310/Orange
      copying Orange/util.py -> build/lib.macosx-11.0-arm64-cpython-310/Orange
      copying Orange/__init__.py -> build/lib.macosx-11.0-arm64-cpython-310/Orange
      (....omission...)
      running build_ext
      building 'Orange.widgets.utils._grid_density' extension
      clang++ -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/mambaforge/base/envs/o3/include -arch arm64 -fPIC -O2 -isystem /opt/homebrew/Caskroom/mambaforge/base/envs/o3/include -arch arm64 -I/private/var/folders/cb/lfh8rrms5ls0kwx5ks1c7pn00000gn/T/pip-build-env-vz64b9xu/overlay/lib/python3.10/site-packages/numpy/_core/include -I/opt/homebrew/Caskroom/mambaforge/base/envs/o3/include/python3.10 -c Orange/widgets/utils/_grid_density.cpp -o build/temp.macosx-11.0-arm64-cpython-310/Orange/widgets/utils/_grid_density.o
      Orange/widgets/utils/_grid_density.cpp:1:10: fatal error: 'map' file not found
          1 | #include <map>
            |          ^~~~~
      1 error generated.
      error: command '/usr/bin/clang++' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Orange3
Failed to build Orange3
```

**Comment by markotoplak** [comment]
@bsnresearcher, this should not be connected with Orange, it shows a misconfigured compiler, who can't find its standard library. I have no idea how compilers work on MacOS lately, but when I was building Orange there I do not remember installing anything but Xcode (or its subset, Command Line Tools). 

I hope someone using MacOS has a more actionable advice.
